spring:
  application:
    name: REST-User

server:
  port: 9002
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbusuario
    username: root
    password: mysql
